---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: sonarqube_server
    run_list:
      - recipe[apt]
      - recipe[java]
      - recipe[sonarqube]
    attributes:
      java:
        jdk_version: '8'
        oracle:
          accept_oracle_download_terms: true
        install_flavor: oracle
  - name: sonarqube_server_mysql
    excludes:
      - ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[java]
      - recipe[sonarqube_mysql]
      - recipe[sonarqube]
    attributes:
      java:
        jdk_version: '8'
        oracle:
          accept_oracle_download_terms: true
        install_flavor: oracle
      sonarqube:
        jdbc:
          url: jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
  - name: sonarqube_scanner
    run_list:
      - recipe[sonarqube::scanner]
  - name: sonarqube_plugin
    run_list:
      - recipe[apt]
      - recipe[java]
      - recipe[sonarqube]
      - recipe[sonarqube_plugin_consumer]
    attributes:
      java:
        jdk_version: '8'
        oracle:
          accept_oracle_download_terms: true
        install_flavor: oracle
